name: Test Self Hosted Runner

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Runner check
        run: |
          echo "Runner berhasil dipanggil"
          hostname
          whoami
